"use client";

import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CardContext } from "./_context/CardContext";
import { useState } from "react";

const inter = Roboto({ subsets: ["latin"], weight: "700" });

// export const metadata = {
//   title: "Next E-Commerce",
//   description: "Generated by Shireff Nady",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([])
  return (
    <ClerkProvider>
      <CardContext.Provider value={{cart, setCart}}>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CardContext.Provider>
    </ClerkProvider>
  );
}
